root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/main ."
bin = "tmp/main"
include_ext = ["go", "yaml", "yml", "toml"]
exclude_dir = ["tmp", "bin", "logs", "vendor", "node_modules"]
exclude_regex = ["_test.go"]
delay = 1000

[misc]
clean_on_exit = true
