// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	"github.com/ishi-o/go_demo/hertz_demo/biz/middleware"
	api "github.com/ishi-o/go_demo/hertz_demo/biz/router/api"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	// INSERT_POINT: DO NOT DELETE THIS LINE!
	r.Use(
		middleware.ErrorHandlerMiddleware(),
		middleware.RespHandlerMiddleware(),
	)
	api.Register(r)
}
